CREATE TABLE product.t_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   description VARCHAR(255),
   CONSTRAINT pk_t_role PRIMARY KEY (id)
);


CREATE TABLE product.t_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   full_name VARCHAR(255),
   email_id VARCHAR(255),
   user_id VARCHAR(255),
   password VARCHAR(255),
   created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   last_modified_date TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_t_user PRIMARY KEY (id)
);

ALTER TABLE product.t_user ADD CONSTRAINT uc_t_user_email UNIQUE (email_id);


CREATE TABLE product.t_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   token VARCHAR(255),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   expires_at TIMESTAMP WITHOUT TIME ZONE,
   validated_at TIMESTAMP WITHOUT TIME ZONE,
   user_id BIGINT NOT NULL,
   CONSTRAINT pk_t_token PRIMARY KEY (id)
);

ALTER TABLE product.t_token ADD CONSTRAINT FK_T_TOKEN_ON_USERID FOREIGN KEY (user_id) REFERENCES product.t_user (id);

CREATE TABLE product.t_user_roles (
  roles_id BIGINT NOT NULL,
   users_id BIGINT NOT NULL
);

ALTER TABLE product.t_user_roles ADD CONSTRAINT fk_tuserol_on_role FOREIGN KEY (roles_id) REFERENCES product.t_role (id);

ALTER TABLE product.t_user_roles ADD CONSTRAINT fk_tuserol_on_user FOREIGN KEY (users_id) REFERENCES product.t_user (id);